### ISSUE TITLE
pvaClientJava doesn't do RPC

### ISSUE THREAD

**Issue by dhickin** [epics-base/pvaClientJava#12]
Use case:
We want to be able to create a channel and create both a channel monitor and channel RPC to that channel. This can't be doesn't through pvaClient currently as it doesn't support RPC. Would need to be able to specify pvRequest in the RPC.

Alternatives are
1) using low-level API
2) Use combination of rcpClient and pvaClient (but need to create multiple channels)

Java is the priority language for the feature for us.

**Comment by gregoryraymondwhite** [comment]
Hi Dave, we (I) also very much want this feature. I thought you had it in hand and were deploying a solution in 4.6? Is that not the case? Puzzled by it’s being put in an issue just now, at this time.

Greg

**Comment by anjohnson** [comment]
@gregoryraymondwhite I think the distinction is between the low-level pvAccess implementation being able to do this and the pvaClient wrapper; I believe the functionality was added to pvAccess but not yet to the client wrapper libraries.

**Comment by mrkraimer** [comment]
Done

**Comment by mrkraimer** [comment]
Done
